# Generated by Django 2.2.1 on 2019-05-12 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_produtos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtos',
            new_name='Produto',
        ),
    ]
