# Generated by Django 2.2.1 on 2019-05-15 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20190512_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='produto',
            new_name='nome_produto',
        ),
    ]
