# Generated by Django 2.2.1 on 2019-06-02 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20190530_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
